# Generated by Django 3.2.13 on 2022-09-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20220915_2304'),
        ('cuotas', '0002_remove_cuota_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuota',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfil'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='anio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='mes',
            field=models.IntegerField(default=0),
        ),
    ]
