# Generated by Django 3.2.13 on 2022-11-03 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0003_auto_20220915_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='fecha_pago',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
