# Generated by Django 3.2.13 on 2022-11-09 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pago',
            new_name='Payment',
        ),
    ]
