# Generated by Django 3.2.13 on 2022-06-07 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_instalacion', models.CharField(max_length=100)),
                ('desc_instalacion', models.TextField(blank=True, null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=5)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='images')),
            ],
        ),
    ]
