# Generated by Django 3.2.13 on 2022-09-16 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_remove_reserva_usuario'),
        ('usuarios', '0002_auto_20220915_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.perfil'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_cancelacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_hora_desde',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='fecha_hora_hasta',
            field=models.DateTimeField(),
        ),
    ]
